#                          #
# #   # ####   ###   ###   #
# #   # #   # #  ## #   #  #
# #   # ####  # # #    #   #
# ##### #   # # # #   #    #
# #   # #   # ##  #  #     #
# #   # ####   ###  #####  #
#                          #
# Hungry Hub Plugin, made by HungryBoy02 (HB02) #
# V1.0                                          #

BlockHunt Hub:
 world: 'world'
 X: 0
 Y: 64
 Z: 0
lWorld: 'world'
# The world to send the player when they run /bh leave (aka your hubworld, if you do not know your hubworld, leave it as 'world') #
# Can also be set with /bh setlworld when in your hubworld. #